/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package week13_kasus1;

/**
 *
 * @author USER
 */
import javax.swing.*;
import java.awt.*;
public class kasus1 extends javax.swing.JPanel {
public static void main(String[]args){
    JFrame frame = new JFrame("Gui Swing");
    
    JLabel label1 = new JLabel("String 1");
    JTextField text1 = new JTextField(10);
    JLabel label2 = new JLabel("String 2");
    JTextField text2 = new JTextField(10);
    JLabel label3 = new JLabel("Hasil");
    JTextField text3 = new JTextField(20);
    JButton btn1 = new JButton("Proses");
    JButton btn2 = new JButton("Hasil");
    
    GridLayout layout = new GridLayout(5,5);
    layout.setHgap(5);
    layout.setVgap(10);

    frame.getContentPane().setLayout(layout);
    frame.getContentPane().add(label1);
    frame.getContentPane().add(text1);
    frame.getContentPane().add(label2);
    frame.getContentPane().add(text2);
    frame.getContentPane().add(label3);
    frame.getContentPane().add(text3);
    frame.getContentPane().add(btn1);
    frame.getContentPane().add(btn2);

    
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.show();
    

}
    /**
     * Creates new form kasus1
     */
    public kasus1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
