/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package week13_latihan12;

/**
 *
 * @author USER
 */
import javax.swing.*;
import java.awt.*;
public class lat12 extends javax.swing.JPanel {
    public static void main(String[]args){
    JFrame frame = new JFrame("textfield");
    JTextField text1, text2, text3, text4;
    text1 = new JTextField("Text 1");
    text2 = new JTextField("Text 2");
    text3 = new JTextField("Text 3");
    text4 = new JTextField("Text 4");
    
    Box pane1 = new Box(BoxLayout.Y_AXIS);
    pane1.add(text1);
    pane1.add(text2);
    pane1.add(text3);
    pane1.add(text4);
    
    frame.getContentPane().setLayout(new FlowLayout(FlowLayout.LEFT));
    frame.getContentPane().add(pane1);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.show();
    }
    /**
     * Creates new form lat12
     */
    public lat12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
