/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package week13_latihan9;

/**
 *
 * @author USER
 */
import javax.swing.*;
import java.awt.*;
public class lat9 extends javax.swing.JPanel {
    public static void main(String[]args){
    JFrame frame = new JFrame("JPanel");
    JPanel pane1 = new JPanel(new GridLayout(2,3));
    JPanel pane2 = new JPanel();
    JPanel pane3 = new JPanel(new BorderLayout(2,3));
    
    pane1.add(new JButton("Button 1"));
    pane3.add(new JButton("Button 2"));
    pane1.add(new JTextArea("Text 1"));
    
    pane3.add(new JButton("1"));
    pane3.add(new JButton("Button 1"));
    
    pane2.add(new JTextArea("text 1"));
    pane2.add(pane3);
    
    frame.getContentPane().add(pane1, BorderLayout.NORTH);
    frame.getContentPane().add(pane2, BorderLayout.SOUTH);
    
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.show();
    }
    /**
     * Creates new form lat9
     */
    public lat9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
