/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package week13_latihan11;

/**
 *
 * @author USER
 */
import javax.swing.*;
public class lat11 extends javax.swing.JPanel {
    public static void main(String[]args){
    JFrame frame = new JFrame("demo html");
    
    String html = "<html>\n"+
                  "contoh penggunaan HTML dalam label:\n"+
                  "<ul>\n"+
                  "<li><font color = red>merah</font>\n"+
                  "<li><font color = green>hijau</font>\n"+
                  "<li><font color = yellow>kuning</font>\n"+
                  "<li><font size =-2>dilangit yang</font>\n"+
                  "<li><font color = blue>biru</font>\n"+
            
                  "<li><font size =-2>bintang kecil ?></font>\n"+
                  "<li><font size =+2>besar ??</font>\n"+
                  "<li><i>italic</i>\n"+
                  "<li><b>bold</b>\n"+
                  "</ul>\n";
    
                  JLabel label = new JLabel(html);
                  frame.getContentPane().add(label);
                  frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                  frame.pack();
                  frame.show();
    }

    /**
     * Creates new form lat11
     */
    public lat11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
